export const preguntas = [
  "¿Cómo calificarías tu nivel de energía al despertar?",
  "¿Qué tan bien estás durmiendo últimamente?",
  "¿Cómo ha sido tu apetito en los últimos días?",
  "¿Qué tan frecuentemente sientes tristeza sin razón clara?",
  "¿Cómo describirías tu capacidad para concentrarte?",
  "¿Cómo te sientes emocionalmente en general?",
  "¿Qué tan motivado te sientes para cumplir tus tareas diarias?",
  "¿Qué tan frecuentes son tus pensamientos negativos?",
  "¿Cómo calificarías tu interés en tus pasatiempos?",
  "¿Qué tan conectado te sientes con las personas que te rodean?",
  "¿Qué tan fácilmente manejas situaciones estresantes?",
  "¿Cómo ha sido tu autoestima recientemente?",
  "¿Qué tan optimista estás sobre el futuro?",
  "¿Qué tan fácil te resulta expresar tus emociones?",
  "¿Qué tan satisfecho estás con tus relaciones personales?",
  "¿Cómo ha sido tu productividad en los últimos días?",
  "¿Qué tan frecuentemente te sientes ansioso?",
  "¿Qué tan en control te sientes de tu vida actualmente?",
  "¿Cómo te sientes contigo mismo al final del día?",
  "¿Qué tan satisfecho estás con tu aspecto físico?",
  "¿Qué tan frecuentemente sientes que no vales lo suficiente?",
  "¿Cómo describirías tu interés por aprender cosas nuevas?",
  "¿Qué tan bien te estás cuidando (alimentación, higiene, descanso)?",
  "¿Qué tan fácil te resulta mantener una actitud positiva?",
  "¿Qué tan satisfecho estás con tu rendimiento académico o laboral?",
  "¿Qué tan fácil te resulta tomar decisiones importantes?",
  "¿Qué tan estable ha sido tu estado de ánimo en los últimos días?",
  "¿Qué tan frecuentemente experimentas emociones agradables?",
  "¿Qué tan cómodo te sientes hablando con otros sobre tus sentimientos?",
  "¿Qué tan satisfecho estás con tu vida en general?"
];
